# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/main/main.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_processing_system7_0_0 || ORIG_REF_NAME==main_processing_system7_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_gpio_0_0/main_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_axi_gpio_0_0 || ORIG_REF_NAME==main_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_gpio_0_1/main_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_axi_gpio_0_1 || ORIG_REF_NAME==main_axi_gpio_0_1} -quiet] -quiet

# IP: bd/main/ip/main_axi_gpio_0_2/main_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_axi_gpio_0_2 || ORIG_REF_NAME==main_axi_gpio_0_2} -quiet] -quiet

# IP: bd/main/ip/main_xbar_0/main_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_xbar_0 || ORIG_REF_NAME==main_xbar_0} -quiet] -quiet

# IP: bd/main/ip/main_ps7_0_axi_periph_0/main_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main/ip/main_rst_ps7_0_50M_0/main_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/main/ip/main_DAC_0_0/main_DAC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_DAC_0_0 || ORIG_REF_NAME==main_DAC_0_0} -quiet] -quiet

# IP: bd/main/ip/main_PUART_0_0/main_PUART_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_PUART_0_0 || ORIG_REF_NAME==main_PUART_0_0} -quiet] -quiet

# IP: bd/main/ip/main_auto_pc_0/main_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_auto_pc_0 || ORIG_REF_NAME==main_auto_pc_0} -quiet] -quiet

# XDC: bd/main/main_ooc.xdc
