# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LASERCOM/LASERCOM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM || ORIG_REF_NAME==LASERCOM} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_processing_system7_0_0/LASERCOM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_processing_system7_0_0 || ORIG_REF_NAME==LASERCOM_processing_system7_0_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_axi_gpio_0_0/LASERCOM_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_axi_gpio_0_0 || ORIG_REF_NAME==LASERCOM_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_axi_gpio_1_0/LASERCOM_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_axi_gpio_1_0 || ORIG_REF_NAME==LASERCOM_axi_gpio_1_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_axi_gpio_2_0/LASERCOM_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_axi_gpio_2_0 || ORIG_REF_NAME==LASERCOM_axi_gpio_2_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_xbar_0/LASERCOM_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_xbar_0 || ORIG_REF_NAME==LASERCOM_xbar_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_ps7_0_axi_periph_0/LASERCOM_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_ps7_0_axi_periph_0 || ORIG_REF_NAME==LASERCOM_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_rst_ps7_0_50M_0/LASERCOM_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_rst_ps7_0_50M_0 || ORIG_REF_NAME==LASERCOM_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_PUART_0_0/LASERCOM_PUART_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_PUART_0_0 || ORIG_REF_NAME==LASERCOM_PUART_0_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_DAC_0_0/LASERCOM_DAC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_DAC_0_0 || ORIG_REF_NAME==LASERCOM_DAC_0_0} -quiet] -quiet

# IP: bd/LASERCOM/ip/LASERCOM_auto_pc_0/LASERCOM_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LASERCOM_auto_pc_0 || ORIG_REF_NAME==LASERCOM_auto_pc_0} -quiet] -quiet

# XDC: bd/LASERCOM/LASERCOM_ooc.xdc
