# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jason/Dev/LaserCom/LASERCOM/LASERCOM.srcs/sources_1/bd/LASERCOM/ip/LASERCOM_auto_pc_0/LASERCOM_auto_pc_0.xci
# IP: The module: 'LASERCOM_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/Dev/LaserCom/LASERCOM/LASERCOM.srcs/sources_1/bd/LASERCOM/ip/LASERCOM_auto_pc_0/LASERCOM_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LASERCOM_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jason/Dev/LaserCom/LASERCOM/LASERCOM.srcs/sources_1/bd/LASERCOM/ip/LASERCOM_auto_pc_0/LASERCOM_auto_pc_0.xci
# IP: The module: 'LASERCOM_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/Dev/LaserCom/LASERCOM/LASERCOM.srcs/sources_1/bd/LASERCOM/ip/LASERCOM_auto_pc_0/LASERCOM_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LASERCOM_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
